package lox;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, SLASH, STAR, SEMICOLON,

    EQUAL, EQUAL_EQUAL,
    NOT, NOT_EQUAL,
    LESS, LESS_EQUAL,
    GREATER, GREATER_EQUAL,
    QUESTION, COLON,

    IDENTIFIER, STRING, NUMBER,

    AND, OR, IF, ELSE, WHILE, FOR, TRUE, FALSE,
    NUL, PRINT, RETURN, SUPER, THIS, VAR, CLASS,
    FUNCTION,

    EOF
}
